# fly.toml app configuration file generated for ssh-terminal-portfolio on 2026-04-21T19:25:49-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ssh-terminal-portfolio'
primary_region = 'sjc'

[build]

[env]
  PORT = '2222'

[http_service]
  internal_port = 2222

[[services]]
  protocol = 'tcp'
  internal_port = 2222

  [[services.ports]]
    port = 22

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = 'ssh_data'
  destination = '/data'